# Generated by Django 2.0 on 2020-03-10 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200310_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='count_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 10, 5, 15, 43, 971686, tzinfo=utc)),
        ),
    ]
