# Generated by Django 2.0 on 2020-03-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200310_1315'),
    ]

    operations = [

    ]
