# Generated by Django 2.0 on 2020-03-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200310_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='own',
        ),
        migrations.DeleteModel(
            name='sight',
        ),
    ]
