# Generated by Django 2.0 on 2020-03-10 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day_sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.IntegerField()),
                ('date', models.DateField(verbose_name=datetime.datetime(2020, 3, 10, 8, 23, 42, 823422, tzinfo=utc))),
            ],
        ),
    ]
