# Generated by Django 2.0 on 2020-03-10 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_sight',
            name='date',
        ),
        migrations.AddField(
            model_name='day_sight',
            name='read_date',
            field=models.DateField(default=67.33333333333334, verbose_name=datetime.datetime(2020, 3, 10, 8, 28, 22, 667942, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
