# Generated by Django 2.0 on 2020-03-10 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20200310_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_sight',
            name='read_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 10, 8, 35, 6, 292282, tzinfo=utc)),
        ),
    ]
