# Generated by Django 2.0 on 2020-03-11 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20200310_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day_sight',
            options={'ordering': ['-read_date']},
        ),
        migrations.AlterField(
            model_name='day_sight',
            name='read_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 11, 12, 20, 4, 900790, tzinfo=utc)),
        ),
    ]
