# Generated by Django 2.0 on 2020-03-18 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20200311_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_sight',
            name='read_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 18, 1, 48, 46, 197143, tzinfo=utc)),
        ),
    ]
