# Generated by Django 2.0 on 2020-03-18 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20200318_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_sight',
            name='read_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 18, 2, 15, 35, 591768, tzinfo=utc)),
        ),
    ]
