# Generated by Django 2.0 on 2020-03-18 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20200318_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_sight',
            name='read_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 18, 2, 37, 35, 717730, tzinfo=utc)),
        ),
    ]
