# Generated by Django 2.0 on 2020-03-18 02:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20200318_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_sight',
            name='read_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 18, 2, 43, 2, 10572, tzinfo=utc)),
        ),
    ]
