# Generated by Django 2.0 on 2020-03-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_time']},
        ),
    ]
