# Generated by Django 2.0 on 2020-03-09 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebsite', '0003_auto_20200308_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='read_count',
        ),
        migrations.AddField(
            model_name='read_count',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blogWebsite.Blog'),
        ),
    ]
