# Generated by Django 2.0 on 2020-03-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebsite', '0005_auto_20200310_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read_count',
            name='date',
        ),
    ]
